### PR TITLE
fix: handle renamed dependencies correctly

### LINKED ISSUE #59: Cargo cannot find renamed dependency from crates-io in package from different registry
See https://github.com/rust-lang/cargo/issues/14399
As I found out, this is a bug in this package, not in cargo.

### PR DESCRIPTION
**Pull request by StackOverflowExcept1on**
Resolves #59. See issue for more details. This PR fixes the handling of renamed dependencies (previously `bar = { version = "1.0", package = "foo" }` was handled incorrectly). I also added .gitignore file.

@d-e-s-o It would be nice to create release on crates.io right after this commit.

### CODE REVIEW

**Comment by d-e-s-o** [comment]
Interesting. Could you add a test case for this issue?

**Comment by StackOverflowExcept1on** [comment]
@d-e-s-o Hmm, I'm not sure how to add complex test, but this fixed my issue in this repo: https://github.com/StackOverflowExcept1on/cargo-bug

**Comment by StackOverflowExcept1on** [comment]
I've encountered another issue with renamed dependencies in my workspace. It seems that cargo-http-registry doesn't support the latest changes https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/registry-index.md. It seems issue #61 occurs because `features2` key is not processed. Minimal example: https://github.com/StackOverflowExcept1on/cargo-bug/commit/8c7b35bdb8c9b8a0796aa82810c2510c9a7cf00d

**Comment by d-e-s-o** [comment]
Thanks!

**Pull request merged**
