### PR TITLE
Move indexes to index folder

### LINKED ISSUE #2: Using with cargo-local-registry
Hello, is it feasible to use this implementation with [cargo local registry](https://crates.io/crates/cargo-local-registry) I would love to sync dependencies before publishing locally.

### PR DESCRIPTION
**Pull request by metaclips**
This adds a folder called index where all crate indexes are stored. Allowing compatibility with [cargo-local-registry](https://crates.io/crates/cargo-local-registry)
closes #2 

Former structure was
-> vendor folder
->> all crate index folders
->> all .crate files

New structure is

-> vendor folder
->> index folder
->>> all crate index folders
->> all .crate files

### CODE REVIEW

**Comment by metaclips** [comment]
@d-e-s-o can you please lint the codebase so I can rebase.
Amaziiiiiiiing library by the way.

**Comment by d-e-s-o** [comment]
Thanks! If you are referring to formatting: the crate is formatted, I believe. You can use the following `rustfmt.toml`:
```
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
edition = "2018"
imports_layout = "Vertical"
match_block_trailing_comma = true
tab_spaces = 2
trailing_semicolon = false
```
If you are referring to `clippy`, just ignore the four issues.

**Comment by d-e-s-o** [comment]
I merged the patch with some minor changes. Thanks for your contribution!

**Comment by metaclips** [comment]
Thanks. This should make development a breeze.

**Pull request closed without merging**
